from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("men/", views.men, name="men"),
    path("contact-us/", views.Contact, name="contact"),
    path("<str:category>/product/<int:pk>/", views.product_detail, name="product_detail"),
    path("add_to_cart/<str:category>/<int:pk>/", views.add_to_cart, name="add_to_cart"),
    path("add_to_wishlist/<str:category>/<int:pk>/", views.add_to_wishlist, name="add_to_wishlist"),
    path("cart/", views.cart_view, name="cart"),
    path("wishlist/", views.wishlist_view, name="wishlist"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
    path('profile/', views.profile, name='profile'),
    path("men/newarrival/", views.men_new_arrivals, name="men_newarrival"),
    path("men/autumn-winter/", views.men_autumn_winter, name="men_autumn_winter"),
    path("men/tshirts/", views.men_tshirts, name="men_tshirts"),
    path("men/polos/", views.men_polos, name="men_polos"),
    path("men/shorts/", views.men_shorts, name="men_shorts"),
    path("men/running/", views.men_running, name="men_running"),
    path("men/yoga/", views.men_yoga, name="men_yoga"),
    path("men/trackpants-joggers/", views.men_trackpants_joggers, name="men_trackpants_joggers"),
    path("women/newarrival/", views.women_new_arrivals, name="women_newarrival"),
    path("women/autumn-winter/", views.women_autumn_winter, name="women_autumn_winter"),
    path("women/tshirts/", views.women_tshirts, name="women_tshirts"),
    path("women/polos/", views.women_polos, name="women_polos"),
    path("women/shorts/", views.women_shorts, name="women_shorts"),
    path("women/trackpants-joggers/", views.women_trackpants_joggers, name="women_trackpants_joggers"),
    path("women/running/", views.women_running, name="women_running"),
    path("women/yoga/", views.women_yoga, name="women_yoga"),
    path("kids/newarrival/", views.kids_new_arrivals, name="kids_newarrival"),
    path("kids/autumn-winter/", views.kids_autumn_winter, name="kids_autumn_winter"),
    path("kids/tshirts/", views.kids_tshirts, name="kids_tshirts"),
    path("kids/polos/", views.kids_polos, name="kids_polos"),
    path("kids/shorts/", views.kids_shorts, name="kids_shorts"),
    path("kids/trackpants-joggers/", views.kids_trackpants_joggers, name="kids_trackpants_joggers"),
    path("kids/running/", views.kids_running, name="kids_running"),
    path("kids/yoga/", views.kids_yoga, name="kids_yoga"),
]